### ISSUE TITLE
Save All

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2#1]
Oddly, the **Save All** option in VS Code is always greyed out for me. 

Occasionally, I just want to save everything with a click. 

Is there a way to activate it?

![VS_Code_Save_All](https://user-images.githubusercontent.com/53196073/98069809-abd29b80-1e2d-11eb-95ab-924d94f2d2d2.png)

(No useful suggestions at **https://github.com/microsoft/vscode/issues/87352**)

**Comment by susanBuck** [comment]
I suspect you may have the "Auto save" functionality enabled - which means by the time you go to the the "File" menu and look for the "Save all" option - the files have already been saved and as a result "Save all" is greyed out.

To check this, search your settings for "Auto save":

![image](https://user-images.githubusercontent.com/237711/98071738-5c429e80-1e32-11eb-878e-e1daf0e3e437.png)

If you have "Auto save" completely disabled, let me know - I can look into what else might by causing "Save all" to not be an option.

**Comment by CrimsonSIS** [comment]
No biggie but I did turn Auto Save off to no effect. I see on the Microsoft github site that there are numerous unresolved issues with this. Will futz with it later...

:-)
