### ISSUE TITLE
'blade'?

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2#2]
(e2framework very kewl. Reminds me of Flask/Django...) What does '**blade**' in 404.**blade**.php indicate? Works locally but anything to do with a blade server?

**Comment by susanBuck** [comment]
Blade is a templating language the framework uses. It provides many shortcuts that can help when authoring view/display code. 

Ref: 
+ Week 9, Part 6 starting at the 8:34 mark: https://www.youtube.com/embed/eeYe8GxobaM?rel=0&showinfo=0
+ https://hesweb.dev/e2/notes/php/e2framework/views

Views are one of the primary things we'll focus on in this weeks videos, so more details coming soon!

**Comment by CrimsonSIS** [comment]
Very sophisticated. Should open source and rebrand as Phpango.

Should we do Project 3 in it?

**Comment by susanBuck** [comment]
It's more modeled after Laravel, but - you'll find lots of similarities amongst many different web frameworks. : )

And yup, just to confirm - P3 is to be built using the e2framework.

**Comment by CrimsonSIS** [comment]
Sort of like Flask. How about PhPlask?

Regarding Week 9: Question 6, 'Composer on production servers.' Not sure that was covered in a video yet but looking at the documentation.

**Comment by susanBuck** [comment]
For reference:

Video: Week 9, Part 2 "Composer and Deployment" 
Starting at the 7:34 mark
https://www.youtube.com/embed/lEF79oec1m8?rel=0&showinfo=0

Notes: https://hesweb.dev/e2/notes/php/composer-deployment#deploy

**Comment by CrimsonSIS** [comment]
Thank you! I was looking at the earlier ones. Last question prior to submission...

Enjoying the course!

:-)

**Comment by CrimsonSIS** [comment]
Reminds me of **{{mustache}}** and **{{handlebars}}**...
