### ISSUE TITLE
Do these two apache restart commands do the same thing?

### ISSUE THREAD

**Issue by CrimsonSIS** [susanBuck/e2#3]
![image](https://user-images.githubusercontent.com/53196073/98727697-571bad00-2366-11eb-83ab-68f313b9e067.png)

FYI: assume the two variations on restart are same on DigitalOcean?

**Comment by susanBuck** [comment]
They're both effectively the same - both will restart Apache. 

Here's a more detailed explanation as to the differences: https://askubuntu.com/a/903405

That explanation is somewhat technical, so **here's my best interpretation/summary of what it's saying**:





The `service` command is a wrapper script that allows system administrators to start, stop, and check the status of services. 

When you run a `service` command, under the hood it's actually resolving to a command from one of the following:

+ `initctl`
+ `/etc/init.d`
+ `systemctl` (The second command we're comparing against)

Given this, I think we can conclude that `service apache2 restart` is effectively a shortcut/alias for `systemctl restart apache2`.

One might choose to use the `systemctl` command directly if they wanted more control than what the `service` "alias" provides.

**Comment by CrimsonSIS** [comment]
DigitalOcean suggested the **systemctl** option, so figured I'd ask. Apache restarted without issuing any exceptions. 👍
